### ISSUE TITLE
Namespace?

### ISSUE THREAD

**Issue by alexfleites** [operativeit/nova-depend-fill#2]
Hola, estoy tratando de usar este paquete tuyo..
eom-plus/nova-depend-fill y en los ejemplos no pones cual es el Use he puesto varios pero siempre me dice que DpendFill no existe,
Alguna idea?

use EomPlus\NovaDependFill\DependFill;

DependFill::make("Vehicle Information")
                ->fields([
                    BelongsTo::make('Vehicle Type', 'type')
                        ->noPeeking()
                        ->showCreateRelationButton()
                        ->sortable(),

**Comment by alexfleites** [comment]
Yo lo que necesito es cuando entren un valor en Plate o VIN Number se propaguen los datos de la DB en marca, Modelo, Año y Color..

https://share.zight.com/o0uOoo9B

**Comment by scramatte** [comment]
Tengo que hacer un commit nuevo.
Pero creo que para lo que necesitas no hace falta ya usar mi componente.

Con el código a continuación puedes ir rellenando listas o campos. 

```php
Select::make('Country', 'country')
    ->searchable()
    ->displayUsingLabels()
    ->options($countries),
Select::make('State', 'state')
    ->searchable()
    ->displayUsingLabels()
    ->readonly()
    ->rules([
        'required',
    ])
    ->dependsOn(
        attributes: ['country'],
        mixin: function (Select $field, NovaRequest $request, FormData $formData) {
            $country = $formData->country;
            if ($country) {
                $states = \App\Models\State::where('code',$country)->pluck('name','code');
                $field->readonly(false)
                      ->options($states);
            }
        },
    ),

```

**Comment by alexfleites** [comment]
Si, pero el problema que tengo es que no son Select son Text y entonces no me captura el OnChange del Input

**Comment by alexfleites** [comment]
Hey, tranquilo, tu solucion trabaja muy bien..
Gracias miles.
https://share.zight.com/jku8dgvb

**Comment by scramatte** [comment]
Ok, perfecto
Entonces cierro el ticket
